## Exploratory Data Analysis

Q1. Which countries have the highest 
    suicide rates per 100k population?

Q2. How have global suicide rates 
    trended over time?

Q3. Does alcohol consumption correlate 
    with suicide rates?

Q4. Does GDP affect suicide rates?
    (Rich countries = safer?)

Q5. Which factor is the STRONGEST 
    predictor of suicide rates?
    (The big reveal 👀)

In [8]:
#importing the necessary libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [9]:
#loading the data
data = pd.read_csv("data.csv")
data.head(10)

,Country,Year,Suicides number,Life expectancy,Adult Mortality,Infant deaths,Alcohol,Under-five deaths,HIV/AIDS,GDP,Population,Income composition of resources,Schooling
0,Albania,2000,54.0,72.6,11.0,1,3.66,1,0.1,1175.788981,38927.0,0.656,10.7
1,Albania,2001,119.0,73.6,14.0,1,4.25,1,0.1,1326.973390,36173.0,0.662,10.6
2,Albania,2002,133.0,73.3,15.0,1,3.73,1,0.1,1453.642777,3511.0,0.670,10.7
3,Albania,2003,124.0,72.8,18.0,1,4.29,1,0.1,189.681557,339616.0,0.674,10.7
4,Albania,2004,146.0,73.0,17.0,1,4.54,1,0.1,2416.588235,326939.0,0.681,10.9
5,Albania,2005,0.0,73.5,15.0,1,5.16,1,0.1,279.142931,311487.0,0.685,10.8
6,Albania,2006,0.0,74.2,99.0,1,5.31,1,0.1,35.129300,2992547.0,0.696,11.4
7,Albania,2007,124.0,75.9,9.0,1,5.58,1,0.1,363.136850,29717.0,0.703,11.6
8,Albania,2008,160.0,75.3,1.0,1,5.61,1,0.1,437.539647,2947314.0,0.713,12.0
9,Albania,2009,0.0,76.1,91.0,1,5.79,1,0.1,4114.136545,2927519.0,0.721,12.2

In [10]:
#inspecting the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1421 entries, 0 to 1420
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          1421 non-null   object
 1   Year                             1421 non-null   int64
 2   Suicides number                  1421 non-null   float64
 3   Life expectancy                  1421 non-null   float64
 4   Adult Mortality                  1421 non-null   float64
 5   Infant deaths                    1421 non-null   int64
 6   Alcohol                          1421 non-null   float64
 7   Under-five deaths                1421 non-null   int64
 8   HIV/AIDS                         1421 non-null   float64
 9   GDP                              1421 non-null   float64
 10  Population                       1421 non-null   float64
 11  Income composition of resources  1421 non-null   float64
 12  Schooling                        1421 non-null   float64
dtypes: float64(9), int64(3), object(1)
memory usage: 144.4+ KB

In [11]:
data.describe()

,Year,Suicides number,Life expectancy,Adult Mortality,Infant deaths,Alcohol,Under-five deaths,HIV/AIDS,GDP,Population,Income composition of resources,Schooling
count,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1421.000000,1.421000e+03,1421.000000,1421.000000
mean,2007.251935,2629.177340,75.233638,116.912738,5.805067,6.664729,7.038705,0.397537,14018.867107,1.294056e+07,0.748189,13.929838
std,4.503817,6755.607644,5.399686,74.413799,13.088297,3.917763,16.104082,2.227681,19697.409425,3.652156e+07,0.160380,2.462661
min,2000.000000,0.000000,53.700000,1.000000,0.000000,0.010000,0.000000,0.100000,1.681350,3.400000e+01,0.000000,0.000000
25%,2003.000000,85.000000,72.500000,68.000000,0.000000,3.540000,0.000000,0.100000,1564.966945,2.541220e+05,0.695000,12.500000
50%,2007.000000,501.000000,74.900000,117.000000,1.000000,6.950000,1.000000,0.100000,4622.415160,1.735275e+06,0.773000,13.800000
75%,2011.000000,1867.000000,78.900000,163.000000,4.000000,9.800000,5.000000,0.100000,16462.485560,7.463157e+06,0.852000,15.600000
max,2015.000000,56958.000000,89.000000,498.000000,111.000000,17.870000,127.000000,29.700000,119172.741800,3.000785e+08,0.948000,20.700000

In [14]:
#Q1. Which countries have the highest suicide rates per 100k population?

top_rates = data.groupby("Country")["Suicides number"].mean()
top_rates = top_rates.sort_values(ascending= False)
print(top_rates)

Country
Russian Federation          40564.125000
United States of America    35969.625000
Japan                       28756.562500
Republic of Korea           12177.937500
Ukraine                     10413.333333
                                ...
Barbados                        2.428571
Maldives                        2.000000
Grenada                         1.200000
Antigua and Barbuda             0.642857
Kiribati                        0.000000
Name: Suicides number, Length: 106, dtype: float64